<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<style>
    table {
        font-size: small;
    }

    table tbody tr td a {
        font-size: small;
    }
</style>
<h3>Halaman Kelola Buku</h3>
<div class="mt-3 ">
    <div class="card p-3">
        <table class="table table-bordered w-100 table-hover">
            <thead>
                <tr>
                    <td class="text-center">No</td>
                    <td class="text-center">Kode Buku</td>
                    <td class="text-center">Judul Buku</td>
                    <td class="text-center">Penulis Buku</td>
                    <td class="text-center">Terbit Buku</td>
                    <td class="text-center">Deskripsi Buku</td>
                    <td class="text-center">Penerbit Buku</td>
                    <td class="text-center">#</td>
                </tr>
            </thead>
            <tbody>
                <?php
                $no = 1;
                foreach ($data as $row) : ?>
                    <tr>
                        <td class="text-center"><?= $no++ ?></td>
                        <td class="text-center"><?= $row['kode_buku'] ?></td>
                        <td><?= $row['judul_buku'] ?></td>
                        <td><?= $row['penulis_buku'] ?></td>
                        <td><?= $row['terbit_buku'] ?></td>
                        <td><?= $row['deskripsi_buku'] ?></td>
                        <td><?= $row['penerbit_buku'] ?></td>
                        <td class="text-center gap-2">
                            <a href="" class="btn btn-warning">Edit</a>
                            <a href="" class="btn btn-warning">Hapus</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>